#!/bin/sh

export HOME=/root
export PATH=/sbin:/bin:/usr/sbin:/usr/bin
export PS1='/ # '

mount -t devtmpfs devtmpfs /dev 2>/dev/null || true
mount -t proc proc /proc
mount -t sysfs sysfs /sys

printf 'Configuring network...\n'
if ip link set eth0 up && udhcpc -i eth0 -q -n -t 5 -T 2; then
    printf '\nNetwork addresses:\n'
    ip addr
    printf '\nDefault route:\n'
    ip route show default
    printf '\nDNS servers:\n'
    if [ -s /etc/resolv.conf ]; then
        cat /etc/resolv.conf
    else
        printf 'No DNS servers received\n'
    fi
else
    printf 'Network configuration failed; continuing without networking.\n'
fi

printf '\nWelcome to Solven\n\n'
cd /
exec setsid cttyhack /bin/sh
